import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState,useRef } from 'react'
import { Inter } from '@next/font/google'
import Footer from 'Components/Footer'
import Navbar from 'Components/Navbar'
import Product from 'models/Product'
import mongoose from 'mongoose'
import styles from '../styles/index.module.css'
import Recommendproducts from 'Components/Recommendproducts'
import Carousel from 'better-react-carousel'
import bgimg from '../assets/images/backgrounds/demo-removebg.png'
import { FaChevronLeft, FaChevronRight } from 'react-icons/fa';
import adidasimg from '../assets/images/backgrounds/adidasshoes.jpg'
import bataimg from '../assets/images/backgrounds/batashoes.jpeg'
import campusimg from '../assets/images/backgrounds/campusshoes.jpg'
import nikeimg from '../assets/images/backgrounds/nikeshoes.jpg'
import pumaimg from '../assets/images/backgrounds/pumashoes.jpg'
import rebookimg from '../assets/images/backgrounds/rebookimages.jpg'
import Link from 'next/link'
import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })


export default function Home({user,logout,addcart,removecart,clearcart,cart,subtotal,products}) {
  const collectionsRef = useRef(null);

  const scrollToCollections = () => {
    collectionsRef.current.scrollIntoView({
      behavior: 'smooth',
      block: 'start',
    });
  };
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></Script>
      </Head>
      <Navbar user={user} logout={logout} heading="HomePage"/>
   
    <div className="flex flex-row items-center justify-between mt-20 h-[80vh]">
         <div className="flex flex-col ml-52 mr-16 mt-28 my-20">
              <div className={styles.slide_in}>
                 <h1 className='text-black-700 text-5xl mb-12 font-bold'>ShoesPedia</h1>
              </div>
              <div className={`text-black-700 mr-20 ${styles.slide_in}`}>
                Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nisi quas veritatis eaque, quis vel quidem. Suscipit totam aliquid, optio beatae alias doloribus perspiciatis. Reprehenderit laboriosam esse, odit cupiditate id accusamus cumque dicta.
              </div>
              <div className={styles.slide_in}>
              <button className='flex items-center space-x-1.5 rounded-lg bg-blue-700 px-4 py-2 text-white duration-100 hover:bg-blue-800 mt-12' onClick={() => scrollToCollections()}>View Collections</button>
              </div>
         </div>
         <div className={`mr-24 ${styles.slide_in}`}>
          <Image src={bgimg} width={1000} height={1000}/>
         </div>     
    </div>
<section className="shoes pt-4" ref={collectionsRef}>
        <h1 className="commonh1 font-bold text-4xl text-center mt-20 mb-12">Collections</h1>
        <div className={styles.row}>
            <Link href='/rebook'><a><div className={`${styles.item_col} suj m-4`}>
                <Image src={rebookimg} className={`${styles.collectionimages} subsuj`} alt="Rebook shoes" style={{width:'400px',height:'400px'}}/>
                <div className={styles.layer}>
                    <h3>Rebook</h3>
                </div>
            </div></a></Link>
            <Link href='/adidas'><a><div className={`${styles.item_col} suj m-4`}>
                <Image src={adidasimg} className={`${styles.collectionimages} subsuj`} alt="Adidas shoes" style={{width:'400px',height:'400px'}}/>
                <div className={styles.layer}>
                    <h3>Adidas</h3>
                </div>
            </div></a></Link>
            <Link href='/nike'><a><div className={`${styles.item_col} suj m-4`}>
                <Image src={nikeimg} className={`${styles.collectionimages} subsuj`} alt="Nike shoes" style={{width:'400px',height:'400px'}}/>
                <div className={styles.layer}>
                    <h3>Nike</h3>
                </div>
            </div></a></Link>
            
        </div>
        <div className={styles.row}>
        <Link href='/bata'><a><div className={`${styles.item_col} suj m-4`}>
                <Image src={bataimg} className={`${styles.collectionimages} subsuj`} alt="bata shoes" style={{width:'400px',height:'400px'}}/>
                <div className={styles.layer}>
                    <h3>Bata</h3>
                </div>
            </div></a></Link>
            <Link href='/campus'><a><div className={`${styles.item_col} suj m-4`}>
                <Image src={campusimg} className={`${styles.collectionimages} subsuj`} alt="campus shoes" style={{width:'400px',height:'400px'}}/>
                <div className={styles.layer}>
                    <h3>Campus</h3>
                </div>
            </div></a></Link>
            <Link href='/puma'><a><div className={`${styles.item_col} suj m-4`}>
                <Image src={pumaimg} className={`${styles.collectionimages} subsuj`} alt="Puma shoes" style={{width:'400px',height:'400px'}}/>
                <div className={styles.layer}>
                    <h3>Puma</h3>
                </div>
            </div></a></Link>
        </div>
    </section>
    <div className="recommend-heading mx-12 my-4">
    <h1 class="sm:text-3xl text-2xl font-medium title-font m-2 text-gray-900 dark:text-gray-100 aos-init aos-animate" data-aos="zoom-in-up" data-aos-anchor-placement="top-bottom">Bestselling Products</h1>
      <div class="h-1 w-20 bg-pink-500 rounded"></div>
    </div>
    {/* <Recommendproducts products={products}/> */}
       <Footer/>
    </>
  )
}

export async function getServerSideProps(context){
  // if(!mongoose.connections[0].readyState){
  //   await mongoose.connect("mongodb://127.0.0.1:27017/Ecommerce");
  // }
  // let products=await Product.find();
  return{
    // props:{products:JSON.parse(JSON.stringify(products))}
    props:{products:null}
  }
}


