name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Docker CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout (optional)
        uses: actions/checkout@v4

      ## The local machine has been registered as a GitHub runner. (Need to run the command './run.sh' in actions-runner folder to start the runner.)
      ## It is assumed that the local machine has kubectl and other required components already set up.
      ## It is also assumed that the correct cluster context is configured (i.e., the Kind cluster is up and running).
      - name: Update Deployment Image
        run: |
          kubectl set image deployment/shoespedia \
            shoespedia=${{ secrets.DOCKERHUB_USERNAME }}/shoespedia:${{ github.sha }} \
            -n shoespedia

      - name: Wait for rollout or Rollback in case of failure
        run: |
          set +e     # disable immediate exit on error

          # Wait for rollout
          kubectl rollout status deployment/shoespedia -n shoespedia --timeout=600s
          ROLLOUT_STATUS=$?

          # Get latest pod
          POD=$(kubectl get pods -n shoespedia -l app=shoespedia \
            --sort-by=.metadata.creationTimestamp \
            -o jsonpath="{.items[-1].metadata.name}")

          echo "Streaming logs from $POD"

          kubectl logs -f $POD -n shoespedia &
          LOG_PID=$!

          sleep 120  # observe logs for some time

          # Stop logs
          kill $LOG_PID

          if [ $ROLLOUT_STATUS -ne 0 ]; then
            echo "Deployment failed! Rolling back..."

            kubectl rollout undo deployment/shoespedia -n shoespedia

            echo "Waiting for rollback..."
            kubectl rollout status deployment/shoespedia -n shoespedia --timeout=300s

            echo "Debug info.."
            kubectl describe pod $POD -n shoespedia

            exit 1
          fi

          echo "Deployment successful!"
