name: Docker CI

on:
  push:
    branches:
    - main

jobs:
  build_scan_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/shoespedia:$GITHUB_SHA .

      - name: Run Docker Scout CVE scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKERHUB_USERNAME }}/shoespedia:$GITHUB_SHA
          only-severities: critical,high
          exit-code: true
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shoespedia:$GITHUB_SHA
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/shoespedia:$GITHUB_SHA \
                    ${{ secrets.DOCKERHUB_USERNAME }}/shoespedia:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shoespedia:latest
